#############################################################################
# Makefile for building: kirkpatrick
# Generated by qmake (2.01a) (Qt 4.8.5) on: Wed Nov 27 05:32:44 2013
# Project:  kirkpatrick.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -o Makefile kirkpatrick.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -g -std=c++11 -Wall -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -Isrc -Ivisualization/headers -I/usr/X11R6/include -I.
LINK          = g++
LFLAGS        = -Wl,-O1,--sort-common,--as-needed,-z,relro -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -L/usr/X11R6/lib -Lvisualization -lvisualization -lQtOpenGL -lQtGui -lQtCore -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = bin/

####### Files

SOURCES       = src/graph.cpp \
		src/kirkpatrick.cpp \
		src/main.cpp \
		src/viewer.cpp 
OBJECTS       = bin/graph.o \
		bin/kirkpatrick.o \
		bin/main.o \
		bin/viewer.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		kirkpatrick.pro
QMAKE_TARGET  = kirkpatrick
DESTDIR       = 
TARGET        = kirkpatrick

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: kirkpatrick.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtOpenGL.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile kirkpatrick.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtOpenGL.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile kirkpatrick.pro

dist: 
	@$(CHK_DIR_EXISTS) bin/kirkpatrick1.0.0 || $(MKDIR) bin/kirkpatrick1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) bin/kirkpatrick1.0.0/ && $(COPY_FILE) --parents src/graph.h src/kirkpatrick.h src/viewer.h bin/kirkpatrick1.0.0/ && $(COPY_FILE) --parents src/graph.cpp src/kirkpatrick.cpp src/main.cpp src/viewer.cpp bin/kirkpatrick1.0.0/ && (cd `dirname bin/kirkpatrick1.0.0` && $(TAR) kirkpatrick1.0.0.tar kirkpatrick1.0.0 && $(COMPRESS) kirkpatrick1.0.0.tar) && $(MOVE) `dirname bin/kirkpatrick1.0.0`/kirkpatrick1.0.0.tar.gz . && $(DEL_FILE) -r bin/kirkpatrick1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

bin/graph.o: src/graph.cpp src/graph.h \
		visualization/headers/geom/primitives/point.h \
		visualization/headers/geom/primitives/vector.h \
		visualization/headers/type_aliases.h \
		visualization/headers/geom/primitives/range.h \
		visualization/headers/geom/primitives/segment.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/graph.o src/graph.cpp

bin/kirkpatrick.o: src/kirkpatrick.cpp visualization/headers/geom/primitives/point.h \
		visualization/headers/geom/primitives/vector.h \
		visualization/headers/type_aliases.h \
		visualization/headers/geom/primitives/range.h \
		visualization/headers/visualization/viewer_adapter.h \
		visualization/headers/visualization/viewer.h \
		visualization/headers/geom/primitives/segment.h \
		src/graph.h \
		src/kirkpatrick.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/kirkpatrick.o src/kirkpatrick.cpp

bin/main.o: src/main.cpp src/viewer.h \
		visualization/headers/visualization/viewer_adapter.h \
		visualization/headers/visualization/viewer.h \
		visualization/headers/geom/primitives/point.h \
		visualization/headers/geom/primitives/vector.h \
		visualization/headers/type_aliases.h \
		visualization/headers/geom/primitives/range.h \
		visualization/headers/geom/primitives/segment.h \
		src/kirkpatrick.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/main.o src/main.cpp

bin/viewer.o: src/viewer.cpp visualization/headers/io/point.h \
		visualization/headers/geom/primitives/point.h \
		visualization/headers/geom/primitives/vector.h \
		visualization/headers/type_aliases.h \
		visualization/headers/geom/primitives/range.h \
		visualization/headers/visualization/draw_util.h \
		visualization/headers/visualization/viewer.h \
		visualization/headers/geom/primitives/segment.h \
		visualization/headers/geom/primitives/rectangle.h \
		visualization/headers/geom/primitives/contour.h \
		visualization/headers/common/range.h \
		src/viewer.h \
		visualization/headers/visualization/viewer_adapter.h \
		src/kirkpatrick.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/viewer.o src/viewer.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

